package com.example.ruiwen.onehouse;/* Generated By:JavaCC: Do not edit this line. CalculatorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalculatorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 2;
  /** RegularExpression Id. */
  int PLUS = 3;
  /** RegularExpression Id. */
  int MINUS = 4;
  /** RegularExpression Id. */
  int TIMES = 5;
  /** RegularExpression Id. */
  int DIVIDE = 6;
  /** RegularExpression Id. */
  int OPEN_PAR = 7;
  /** RegularExpression Id. */
  int CLOSE_PAR = 8;
  /** RegularExpression Id. */
  int BEGINSOLVE = 9;
  /** RegularExpression Id. */
  int BEGINSOLVE2 = 10;
  /** RegularExpression Id. */
  int ENDSOLVE = 11;
  /** RegularExpression Id. */
  int EQUAL = 12;
  /** RegularExpression Id. */
  int SOLVEX = 13;
  /** RegularExpression Id. */
  int SOLVEX2 = 14;
  /** RegularExpression Id. */
  int NUMBER = 15;
  /** RegularExpression Id. */
  int DIGITS = 16;
  /** RegularExpression Id. */
  int SIN = 17;
  /** RegularExpression Id. */
  int COS = 18;
  /** RegularExpression Id. */
  int TAN = 19;
  /** RegularExpression Id. */
  int SQRT = 20;
  /** RegularExpression Id. */
  int LOG10 = 21;
  /** RegularExpression Id. */
  int LN = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<EOL>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"solvex{\"",
    "\"solvex2{\"",
    "\"}\"",
    "\"=\"",
    "\"x\"",
    "\"x^2\"",
    "<NUMBER>",
    "<DIGITS>",
    "\"sin\"",
    "\"cos\"",
    "\"tan\"",
    "\"sqrt\"",
    "\"log\"",
    "\"ln\"",
  };

}
